[package]
name = "unicode-box-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
tui-renderer = { git = "https://github.com/ValynTyler/tui-renderer.git" }
nslice = { git = "https://github.com/ValynTyler/nslice-rs.git" }
